[settings]
lockfile = true

[tools]
lefthook = "latest"
go = "1.25"

[hooks]
postinstall = "lefthook install"

[tasks.build]
run = "go build -o douane ."

[tasks.test]
run = "go test ./..."

[tasks.check]
run = "filet check"

[tasks.install]
run = "GOBIN=$HOME/go/bin go install ."
